WIP: Add title mechanism to captain command
ActiveState/cli pull request #1024
Opened 2020-10-13 16:31 UTC by daved

https://www.pivotaltracker.com/story/show/174261853

2020-10-13 23:22 UTC, daved commented
I'm not sure if commands like _prepare, _protocol, and shim, should our should not have titles. For this PR, I generally favored noisiness, but it may be worth keeping an eye out for commands that should be quieter.

2020-10-14 16:53 UTC, Naatan requested changes

2020-10-14 16:53 UTC, Naatan commented on internal/output/txtstyle/title.go
> +type Title struct {
Let's have this implement output.Marshaller

http://github.com/ActiveState/cli/blob/d657478e6235fe89e8a7bc401c63e60d83349ac3/internal/output/mediator.go#L8-L8

And then only have it output data for the plain outputter, eg.

```
func (t *Title) MarshalOutput(format output.Format) interface{} {
	if format == output.PlainFormatName {
		return t.String()
	}
	return nil
}
```

2020-10-14 16:53 UTC, Naatan commented on internal/output/txtstyle/title.go
> +type Title struct {
We may need to implement some type to mean "don't output this". I think `nil` will just cause it to print something "empty". Could have some type `output.Suppress` that's handled here:

http://github.com/ActiveState/cli/blob/d657478e6235fe89e8a7bc401c63e60d83349ac3/internal/output/mediator.go#L12-L12

2020-10-14 16:53 UTC, Naatan commented on internal/output/txtstyle/title.go
> +	return string(rs[:len(rs)-1]) // drop ending newline
Very cool! My only criticism; can we turn things like `lineLen-2` into variables like `posTopRightCorner`. That would instantly make this whole function a lot easier to grok.

2020-10-14 16:53 UTC, Naatan commented on internal/output/txtstyle/title_test.go
> +		{test: "basic empty", title: "", want: emptyBasic},
I think if it's empty we should just not print anything.

2020-10-14 22:53 UTC, Naatan approved these changes

2020-10-14 22:53 UTC, merged