WIP: Fix activation after update
ActiveState/cli pull request #1101
Opened 2020-11-10 17:15 UTC by daved

https://www.pivotaltracker.com/story/show/175607307

2020-11-10 22:23 UTC, daved commented
@Naatan I ended up adding a new structure (process.Activation) in order to minimize the work required by callers.

The scripts included for testing the updates saved me a tremendous amount of time, so I've included them (fupdstor was written on my own time, and setmod-by-hrs was a script I already had and added a minor update to).

Also, I ran into an issue where the file generated by the PIDLock type is not removed if the process is killed via SIGKILL. I'll file a bug if the source of this issue is not within the current changeset.

2020-11-10 22:28 UTC, Naatan requested changes
Looking good! Just one minor issue.

2020-11-10 22:28 UTC, Naatan commented on internal/updater/check.go
> +	seconds := 2
Undo this please. Guess you did this for your tests, but I did not ask for this to be increased nor would I want it to. If there's an issue here please file a bug.

2020-11-11 00:14 UTC, Naatan approved these changes

2020-11-11 00:16 UTC, merged