Install scripts activate project even if state tool is installed
ActiveState/cli pull request #1106
Opened 2020-11-10 22:39 UTC by mdrohmann

2020-11-10 22:43 UTC, Naatan requested changes
I want our installers to skip over the install logic and just get to the success state. I don't want a whole separate flow if install doesn't need to take place. Just skip over the install flow and get to the success bit. 

In effect; we should only run the activate call in one place. 

If that creates too much need for refactoring / rearchitecting please let me know, that's not the intend here.

2020-11-10 23:06 UTC, mdrohmann commented
It is quite a bit of refactoring. Basically it needs to be organized like the install.ps1 script.  But it should be okay...

2020-11-12 17:21 UTC, Naatan requested changes
I asked you to come talk to me if this required significant refactoring. Please go back to the original commit. I'm not against refactoring but if we're going to invest in that we're going to do it right. All this would do now is land us in an intermediary state with its own set of bugs that will then itself have to be refactored again when we decide to make that investment.

2020-11-12 17:27 UTC, Naatan approved these changes

2020-11-12 17:35 UTC, merged