State projects shows no projects
ActiveState/cli pull request #1141
Opened 2020-11-25 22:59 UTC by MDrakos

This is the sequence of events that can lead to `state projects` showing no projects, even though there is a default activation:

1. `state activate --default` a project (This was done using the one-liner)
2. Install a package
3. Uninstall the state tool (or just remove the config directory)
3. `state activate --default` again with the same project in the same directory

Since we added a package in step 2 the project is now in a headless state. When we add the project mapping to the config we get:

```
projects:
  /:
  - C:\Users\Administrator\ActiveState\Perl-5.32
```

This fix writes the mapping during activation using the namespace parameter. There is also a minor update to the project regex. I've also filed a story [here](https://www.pivotaltracker.com/story/show/175901661) to update our handling of headless projects in the config and with `state projects`

2020-11-26 00:06 UTC, mdrohmann requested changes
So in that case - even with the changes from this PR - the `state projects` command would still not show any projects, because the directory is head-less, no?

Does storing the project configuration during `state activate --default` actually change anything then?  I would think that it should be early enough, as we did it before which was happening whe reading the `activestate.yaml` IIUC.

2020-11-26 00:17 UTC, MDrakos commented
In my testing this does fix the issue. We end up with two entries in the project mapping. The incorrect entry will be written every time the project file is parsed/saved and the correct one is written when a default project is activated. Dealing with the incorrect entry is for the other story I filed. This PR is admittedly more of a quick fix until we know how we want to represent headless projects in the config file.

```
projects:
 /:
  - C:\Users\Administrator\ActiveState\Perl-5.32
 activestate/perl-5.32:
  - C:\Users\Administrator\ActiveState\Perl-5.32
```

2020-11-26 00:39 UTC, mdrohmann requested changes
Interesting.  But is then maybe sufficient to add the line that writes the configuration line early ie., this one: https://github.com/ActiveState/cli/pull/1141/files#diff-0927148580d0b8620ad94bebab7330dc24b7b2d940c17f245f247fb7f51dda85R1238-R1241

If I understand correctly that would be run during an activation with the correct namespace even without the addition of the line in `activate.go`, no?

2020-11-26 18:55 UTC, MDrakos commented
Unfortunately no, it will run during activation but in the scenario outlined above the project is already in a headless state so the key written to the config will still be `/`. 

Thinking about this further I think the correct solution is to have a proper way to represent headless projects in the config and therefore with `state projects`. Maybe we should leave this story in favour of the other one I filed. We just need to settle on a representation.

2020-11-30 17:45 UTC, mdrohmann commented
I think that's what we should do. Let's discuss that in standup today.

On Thu, Nov 26, 2020, 10:55 AM Mike Drakos <notifications@github.com> wrote:

> Unfortunately no, it will run during activation but in the scenario
> outlined above the project is already in a headless state so the key
> written to the config will still be /.
>
> Thinking about this further I think the correct solution is to have a
> proper way to represent headless projects in the config and therefore with state
> projects. Maybe we should leave this story in favour of the other one I
> filed. We just need to settle on a representation.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ActiveState/cli/pull/1141#issuecomment-734443223>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBVTUU3SJ53T6D7N5ZNZQDSR2QCDANCNFSM4UC7SGQQ>
> .
>

2020-11-30 19:02 UTC, MDrakos commented
Closing this as per discussion from standup today. This is a known limitation and a very unique set of circumstances to reproduce.

2020-11-30 19:02 UTC, closed without merging