termtest CI does not recognize some prompt inputs
ActiveState/cli pull request #1145
Opened 2020-11-30 22:53 UTC by mdrohmann

2020-12-01 17:07 UTC, Naatan requested changes
Can we make this the default for `.Send()` and introduce a `.SendUnterminated()` (or whatever you want to name that).

Feel like this is too error prone.

2020-12-01 18:14 UTC, mdrohmann commented
I think you are right, but I actually changed the `conproc.SendLine` function so that it always just sends a simple newline character.  There is now also a function to add an OS aware newline separator `SendOSLine`.

2020-12-01 19:36 UTC, mdrohmann commented
The integration tests are not running right now, because Github Actions are degraded.  But I tested it locally, and believe that they will eventually pass this way...

2020-12-02 17:02 UTC, Naatan approved these changes

2020-12-02 17:47 UTC, merged