WIP: Add vertical table handling
ActiveState/cli pull request #1163
Opened 2020-12-10 19:02 UTC by daved

https://www.pivotaltracker.com/story/show/176045967

2020-12-10 19:26 UTC, Naatan requested changes

2020-12-10 19:26 UTC, Naatan commented on internal/output/plain.go
> +	VerticalTable PlainOpts = "tableVert"
```suggestion
	// VerticalTable requests a table be output vertically
	VerticalTable PlainOpts = "verticalTable"
```

2020-12-10 19:26 UTC, Naatan commented on internal/output/plain.go
> +	HorizontalTable PlainOpts = "tableHoriz"
This is the default, don't need an option for this.
```suggestion
```

2020-12-10 19:26 UTC, Naatan commented on internal/table/table.go
> +func verticalRows(hdrs []string, rows []row) []row {
Please undo all this stuff to the table package. As the ACs state the only change here is disregarding the headers.

2020-12-10 23:22 UTC, Naatan approved these changes

2020-12-11 19:16 UTC, daved commented
A followup story is filed here: https://www.pivotaltracker.com/story/show/176100516

2020-12-11 19:34 UTC, Naatan approved these changes

2020-12-11 19:34 UTC, merged