add `state cve` command
ActiveState/cli pull request #1209
Opened 2021-01-15 00:15 UTC by mdrohmann

2021-01-15 17:45 UTC, mdrohmann commented
I don't know if this ready for prime time due to some limitations of the mediator that came up:

Follow-up stories are here: 
- https://www.pivotaltracker.com/story/show/176519572
- https://www.pivotaltracker.com/story/show/176508772
- https://www.pivotaltracker.com/story/show/176508740

The first one might be a blocker for putting it on production...

2021-01-15 18:10 UTC, Naatan requested changes
Very nice work! Just one super nitpicky change.

2021-01-15 18:10 UTC, Naatan commented on cmd/state/internal/cmdtree/cve.go
> +		locale.Tl("cve_description", "Print project vulnerabilities"),
```suggestion
		locale.Tl("cve_description", "Show a summary of CVE vulnerabilities"),
```

2021-02-12 21:18 UTC, mdrohmann commented
I added the changes that were necessary to work with the updated mediator.  Of course, this does not work yet, with the production endpoint for the mediator.

2021-02-12 21:39 UTC, Naatan submitted a review, later dismissed

2021-02-13 00:55 UTC, mdrohmann commented
Took a little while until the mediator was deployed, because kubernetes ran out of some resources, but now everything seems to be working.  Just need another approval for the latest additions that I had to do...

2021-02-13 01:16 UTC, Naatan approved these changes

2021-02-13 03:30 UTC, merged