add ArgMarshaler for package@version args
ActiveState/cli pull request #1215
Opened 2021-01-25 18:30 UTC by mdrohmann

2021-01-26 17:55 UTC, mdrohmann commented
This unifies the behavior for arguments of `language@version`, `platform@version`, `package@version` and `channel@version`.

2021-01-26 19:35 UTC, MDrakos requested changes
I wonder if `captain` is the right place for `nameversion.go`. That or maybe the types are too specific to our commands? I'm not sure if it's appropriate to give `captain` knowledge of what a `PackageVersion` is. Though I will defer to @Naatan for his thoughts.

Other than that I like how it's used in the runners and only noted two minor comments to address.

2021-01-26 19:35 UTC, MDrakos commented on internal/captain/nameversion.go
> +		return errors.New("invalid format")
I think this needs localization and also could be a more descriptive error

2021-01-26 19:35 UTC, MDrakos commented on internal/config/config_test.go
> +	suite.T().Skip()
Was this for debugging?

2021-01-26 20:18 UTC, mdrohmann commented on internal/config/config_test.go
> +	suite.T().Skip()
Thanks for catching!

2021-01-26 20:26 UTC, mdrohmann commented
I think you are right about the location for the `NameVersion` specializations.  I moved the specializations to their respective runners.

2021-01-26 23:35 UTC, MDrakos submitted a review, later dismissed

2021-01-26 23:53 UTC, Naatan requested changes

2021-01-26 23:53 UTC, Naatan commented on internal/runners/packages/packages.go
> +		return locale.NewError("err_package_format", "The package and version provided is not formatting correctly, must be in the form of <package>@<version>")
Should be an input error

2021-01-26 23:53 UTC, Naatan commented on internal/captain/nameversion.go
> +		return locale.NewError("name_version_format_err", "Invalid format: Should be <name@version>")
Should be input error

2021-01-26 23:53 UTC, Naatan commented on internal/runners/platforms/platforms.go
> +		return locale.NewError("err_platform_format", "The platform and version provided is not formatting correctly, must be in the form of <platform>@<version>")
Input error

2021-01-27 00:28 UTC, Naatan requested changes
You're also loosing the original error I just noticed. Should be WrapInputError not NewInputError.

2021-01-27 02:25 UTC, Naatan approved these changes

2021-01-27 17:35 UTC, merged