Notify log out/in rather than force logout
ActiveState/cli pull request #1259
Opened 2021-02-17 23:18 UTC by daved

2021-02-17 23:20 UTC, Naatan reviewed
I like the idea of adding a tip here, but the tips themselves are meant to be suuuper short and to the point, eg. "Logout with `state auth logout`".

2021-02-17 23:21 UTC, daved commented
@Naatan This will produce an effect only in some cases since we generally reach this code using `authentication.Get()`. In other words, the error w/tip will not propagate in most cases. I'm not sure how else to resolve this without touch many file.

2021-02-17 23:26 UTC, Naatan commented
> @Naatan This will produce an effect only in some cases since we generally reach this code using `authentication.Get()`. In other words, the error w/tip will not propagate in most cases. I'm not sure how else to resolve this without touch many file.

That's fine. Removing `auth.Get()` is its own story.

2021-02-17 23:37 UTC, Naatan requested changes

2021-02-17 23:37 UTC, Naatan commented on pkg/platform/authentication/auth.go
> +			locale.T("logout_tip", "Login with[ACTIONABLE]`state auth`[/RESET]."),
```suggestion
			locale.T("logout_tip", "Logout with [ACTIONABLE]`state auth logout`[/RESET]."),
			locale.T("logout_tip", "Login with [ACTIONABLE]`state auth`[/RESET]."),
```

2021-02-17 23:37 UTC, Naatan commented on pkg/platform/authentication/auth.go
> +			locale.T("relog_tip", "If you're seemingly logged in already, try logging out and in again."),
```suggestion
			locale.T("relog_tip", "If you're having trouble authenticating try logging out and logging back in again."),
```

2021-02-18 00:17 UTC, Naatan approved these changes

2021-02-18 00:23 UTC, merged