Rename `state cve`
ActiveState/cli pull request #1286
Opened 2021-03-15 21:13 UTC by MDrakos

2021-03-15 21:55 UTC, Naatan requested changes

2021-03-15 21:55 UTC, Naatan commented on changelog.md
> +### Added
```suggestion
### Changed
```

2021-03-15 22:09 UTC, Naatan approved these changes

2021-03-16 06:51 UTC, mdrohmann approved these changes

2021-03-18 23:54 UTC, merged