Installers `-c` flag
ActiveState/cli pull request #1289
Opened 2021-03-19 18:27 UTC by MDrakos

2021-03-24 17:01 UTC, mdrohmann submitted a review, later dismissed

2021-03-24 21:17 UTC, Naatan requested changes

2021-03-24 21:17 UTC, Naatan commented on test/integration/install_scripts_int_test.go
> +		e2e.WithArgs(script, "-t", ts.Dirs.Work, "-c", "\"state activate ActiveState/Perl-5.32 --default\""),
This is still part of important flows used in production for a while, so I'd rather we add another test than replace this one, at least for now.

2021-03-26 17:08 UTC, Naatan approved these changes

2021-03-26 17:28 UTC, merged