First draft for update warning
ActiveState/cli pull request #1330
Opened 2021-04-28 22:13 UTC by mdrohmann

https://www.pivotaltracker.com/story/show/177827736

It currently looks like this: 
![Selection_030](https://user-images.githubusercontent.com/8608210/116479075-f1e44700-a833-11eb-8439-197814ae48b5.png)

It is a little different from what is asked for [here](https://www.pivotaltracker.com/story/show/177824358/comments/223624674).

2021-04-28 22:46 UTC, Naatan requested changes
This looks good to me. The design needs some tweaking but I'll do that in my PR.

The only thing I'm missing is the part where it checks that the lock is for "older" versions. Ie. we only want to warn about projects that are locked to versions where auto-forwarding was still a thing. Again we can just hardcode that particular version number as a constant.

2021-04-28 22:46 UTC, Naatan commented on cmd/state-update-dialog/app.go
> +		Height: 600,
```suggestion
		Width:  600,
		Height: 400,
```

Don't worry about the design for this PR.

2021-04-29 16:20 UTC, mdrohmann commented
> The only thing I'm missing is the part where it checks that the lock is for "older" versions. Ie. we only want to warn about projects that are locked to versions where auto-forwarding was still a thing. Again we can just hardcode that particular version number as a constant.

I added that check, but I wonder if it is correct... Projects with locks for multi-file updates also get unusable, as they will receive an error message that the project is locked to a version that is not installed anymore.  And for now, the single-file updates are actually forwarded, so they would still work.  So, maybe that check needs to be the other way round?  Or even get removed completely?

2021-04-29 16:25 UTC, Naatan commented
That auto-forwarding will only work for one version after we deploy, after that it won't work anymore. So those would still need the warning.

As for projects with locks for multi-file updates; I'm confused, we discussed this. They will get an error explaining how to install an older version.

The warning is about informing people that this thing that they've gotten used to is going to change. It doesn't change any of our decisions regarding how the locking works.

2021-04-29 16:26 UTC, Naatan approved these changes

2021-04-29 17:05 UTC, mdrohmann commented
> As for projects with locks for multi-file updates; I'm confused, we discussed this. They will get an error explaining how to install an older version.
I know that. But I understood it this way: *This* warning is exactly for that use-case: To inform the user, that they might have to do the installation again (installing an older State Tool version) to use those projects.  So, that's what confuses me...

2021-04-29 17:13 UTC, Naatan commented
> I know that. But I understood it this way: _This_ warning is exactly for that use-case: To inform the user, that they might have to do the installation again (installing an older State Tool version) to use those projects. So, that's what confuses me...

I could get on board with that, if it simplifies things. So this warning would show and instruct them how to install the older version? Or I guess link to the docs that would explain it? And as a result we wouldn't need the auto-forward mechanic in this update at all?

2021-04-29 18:02 UTC, merged