Ensure runtime is updated if executors are missing despite payload being cached
ActiveState/cli pull request #1386
Opened 2021-05-24 23:39 UTC by daved

2021-05-25 16:28 UTC, mdrohmann approved these changes

2021-05-25 17:03 UTC, Naatan requested changes
This looks like a workaround to me. How did we end up in a state where `rt.store.MatchesCommit(target.CommitUUID())` returns true but the executor dir did not exist?

2021-05-25 17:20 UTC, daved commented
I took the commit sanity check to mean that the cache is loaded properly. The executors seem fundamentally different in that regard, so a separate check makes sense to me.

2021-05-25 17:23 UTC, Naatan commented
Executors are created here: http://github.com/ActiveState/cli/blob/0ec4186682f908080e65343ecf63f4e0c7a2c8b3/pkg/platform/runtime/setup/setup.go#L222-L222

The the commit is saved a few lines further down at: http://github.com/ActiveState/cli/blob/0ec4186682f908080e65343ecf63f4e0c7a2c8b3/pkg/platform/runtime/setup/setup.go#L253-L253

Regardless of whether the store and executors are fundamentally different, logically the executors should always exist with the current implementation. The fact that it doesn't is concerning and we should ensure that we understand why it's bugged.

2021-05-25 17:26 UTC, mdrohmann commented
@Naatan This only happens when you have a runtime activated by an old State Tool that hadn't had the executor logic in there yet.  With that old State Tool, the runtime directory would be set up with out the `exec` dir, but the `complete` marker.

Once, they update the State Tool, the runtime will stop working, because we only add the `exec` directory to the PATH which points to a void space...

2021-05-25 17:27 UTC, mdrohmann commented
So, it is transitional, and we should probably remove that check after a few months...

2021-05-25 17:27 UTC, Naatan commented
Ok, in that case can we drop the public functions and just have some really to-the-point code where it needs to be with a comment pointing to a PT ticket saying we should drop this after a while.

2021-05-25 21:32 UTC, daved commented
`filepath.Join(s.target.Dir(), "exec")` was like nails on a chalkboard for me, so I left in the setup.ExecDir func for now (will remove it if you'd like).

2021-05-25 21:34 UTC, Naatan requested changes

2021-05-25 21:34 UTC, Naatan commented on pkg/platform/runtime/runtime.go
> +	// tool versions): https://www.pivotaltracker.com/story/show/178152827
This should link to the followup story to remove this code in due time.

2021-05-26 15:55 UTC, Naatan approved these changes

2021-05-26 16:06 UTC, mdrohmann approved these changes

2021-05-26 16:24 UTC, merged