Implemented merging
ActiveState/cli pull request #1393
Opened 2021-05-27 22:32 UTC by Naatan

2021-05-28 22:18 UTC, mdrohmann approved these changes
Nice work.  Just two small suggestions: one to simplify a boolean check and one test case seems to be running with incorrect arguments.

2021-05-28 22:18 UTC, mdrohmann commented on pkg/platform/model/vcs_internal_test.go
> +				cidp(1), nil, nil, nil,
```suggestion
				nil, nil, nil, nil,
```

2021-05-28 22:18 UTC, mdrohmann commented on internal/runners/pull/pull.go
> +	if targetCommit != nil && (noCommonParent || divergedHistory) {
```suggestion
	if divergedHistory {
```

2021-06-23 18:46 UTC, mdrohmann requested changes
I played around with the code a little bit, and it looks good to me.  Just had two questions, and found an unused function that we can remove.

2021-06-23 22:44 UTC, Naatan commented on internal/runners/pull/pull.go
> -		related, err := areCommitsRelated(*target.CommitID, p.project.CommitUUID())
Because the merge endpoint already detects this for us and gives the proper error codes.

2021-06-23 22:47 UTC, Naatan commented on internal/runners/pull/pull.go
> +			} else if !errors.Is(err, model.ErrMergeCommitInHistory) {
When `ErrMergeCommitInHistory` is returned it means we just need a pull, without a merge. So ignoring it here is the proper action.

2021-06-23 22:50 UTC, mdrohmann approved these changes

2021-06-24 16:59 UTC, merged