Default executors do not reference runtime executors
ActiveState/cli pull request #1411
Opened 2021-06-08 23:42 UTC by MDrakos

2021-06-09 16:38 UTC, Naatan requested changes
I'd rather we treat the cause of the problem rather than the symptom. The problem is that it's detecting executables using `exec` in the PATH right? So we should in the relevant spot split `exec` from the PATH.

I think you can narrow the problem down to this spot:

http://github.com/ActiveState/cli/blob/0dbebe3514e8d135428d7d6af46bbb23b3a61081/pkg/platform/runtime/executor/executor.go#L56-L56

As in that's the most central common denominator. If you find where that function is used you'll find the spots where it's passing in an `envdef.ExecutablePaths` with executors on the PATH.

It looks like the source of the executablePaths is here: http://github.com/ActiveState/cli/blob/0dbebe3514e8d135428d7d6af46bbb23b3a61081/pkg/platform/runtime/envdef/environment.go#L364-L364

But that's suggesting that it's not inheriting any env info, so there might be a bug there.

Key point; let's address the root cause.

2021-06-09 17:16 UTC, MDrakos commented
The `exec` directory is not in `PATH` when `ExecutablePaths` is called; however, the runtime cache directory and some of its sub directories are. Here is an example of the directories that are on `PATH` when `ExecutablePaths` is called:

```
C:\Users\msft-admin\AppData\Local\activestate\3ad3401c 
C:\Users\msft-admin\AppData\Local\activestate\3ad3401c\usr\bin 
C:\Users\msft-admin\AppData\Local\activestate\3ad3401c\bin
```


The issue is that `exeutlils.Executables` walks the file paths it's given, essentially putting anything in the runtime directory and subdirectories on PATH. That is why this PR provides the option to skip a directory if it is encountered.

It might be more appropriate for `exeutils.Executables` to simply list the files in the directories it's given and find executables that way, rather than walking the paths. But this function is also used by deploy and I was not sure how that change might affect it.

2021-06-09 20:30 UTC, Naatan commented
> essentially putting anything in the runtime directory **and subdirectories** on PATH.
> ..  **and subdirectories**

If this is true then that's the bug. It should not be looking for executables in subdirs, as that's not what PATH does either.

2021-06-10 16:57 UTC, Naatan requested changes

2021-06-10 16:57 UTC, Naatan commented on internal/exeutils/exeutils.go
> +		if fileutils.IsExecutable(bin) {
None of the bins themselves can be executables, the original code only looks for executables inside the bin paths.

2021-06-10 16:57 UTC, Naatan commented on internal/exeutils/exeutils.go
> +		if fileutils.IsDir(bin) {
This should always be the case, if anything if this isn't a dir we should return an error.

2021-06-14 17:12 UTC, Naatan approved these changes

2021-06-14 21:39 UTC, merged