Replace cgo based sqlite with go based sqlite
ActiveState/cli pull request #1444
Opened 2021-07-09 16:55 UTC by Naatan

2021-07-09 17:02 UTC, mdrohmann approved these changes
Nice, fast digging.
Let's just hope that modernc.go/sqlite is as stable as the c-library based one.

2021-07-09 17:03 UTC, Naatan commented
> Nice, fast digging.
> Let's just hope that modernc.go/sqlite is as stable as the c-library based one.

Our use of sqlite is so basic that hopefully this won't matter too much. Definitely making me realize how much I rely on Github's star/fork stats to gauge package stability though..

2021-07-09 23:06 UTC, mdrohmann requested changes

2021-07-09 23:06 UTC, mdrohmann commented on internal/config/instance.go
> +	closed      bool
This should probably be guarded by a mutex.  Or maybe you can use a `sync.Once` instance in the `Close()` function to ensure that the thread is closed only once.

2021-07-10 00:36 UTC, mdrohmann approved these changes

2021-07-12 16:53 UTC, merged