Forward output of prepare
ActiveState/cli pull request #1455
Opened 2021-07-19 22:23 UTC by MDrakos

2021-07-19 22:35 UTC, MDrakos commented
Tested this locally updating from `release` to `beta` and produces the following output:

```
mike@ead679a3b7bb:~$ ./cli/build/state update --set-channel beta
╔═════════════════════════╗
║ Updating The State Tool ║
╚═════════════════════════╝
Updating State Tool to latest version available.
Updating state tool:  Downloading latest version of the state tool...

Installing version 0.29.0-SHAbdb136a
Install Location: /home/mike/.local/ActiveState/StateTool/beta
Stopping services
Updating environment
Starting ActiveState Desktop
Installation Complete
Please start a new shell in order to start using the ActiveState Desktop tools.
Please start a new shell to continue using the State Tool.
Version updated to beta@0.29.0-SHAbdb136a
```

2021-07-26 20:10 UTC, Naatan requested changes

2021-07-26 20:10 UTC, Naatan commented on internal/updater/updater.go
> +	cmd.Stdin = os.Stdin
Stdin shouldn't be part of this

2021-07-26 22:34 UTC, Naatan approved these changes

2021-07-27 19:25 UTC, merged