Handle panics in analytics and logging/rollbar
ActiveState/cli pull request #1531
Opened 2021-09-03 22:45 UTC by mdrohmann

https://www.pivotaltracker.com/story/show/179457181

2021-09-03 22:47 UTC, mdrohmann commented on cmd/state-installer/installer.go
> +		if err := events.WaitForEvents(1*time.Second, analytics.Wait, rollbar.Close, authentication.LegacyClose); err != nil {
I am fairly sure that adding `analytics.Wait` here, fixes the root problem ie., the bug observed by Jeremy.

As the analytics functions may trigger a logging error event that creates a rollbar message, we should wait for the analytics (background) processes to finish before we are closing the rollbar.  That will avoid this issue in the future.

2021-09-07 22:12 UTC, Naatan requested changes

2021-09-07 22:12 UTC, Naatan commented on internal/logging/logging.go
> +	fmt.Fprintf(os.Stderr, "Panic occurred in logging module: %v\n", err)
```suggestion
	fmt.Fprintf(os.Stderr, "Failed to log error. Please report this on the forums if it keeps happening. Error: %v\n", err)
```

2021-09-07 22:14 UTC, Naatan approved these changes

2021-09-07 22:22 UTC, Naatan approved these changes

2021-09-08 17:14 UTC, merged