Update push branch check
ActiveState/cli pull request #1636
Opened 2021-11-16 17:42 UTC by MDrakos

Judging from the ticket I think this is the behaviour we want.

1. User is on a non-default branch of a project
2. `state push <new/namespace>`
3. state push creates a new project. The new project's default branch has the latest commit from (1)

2021-11-17 21:17 UTC, Naatan reviewed
-removed-

2021-11-17 21:46 UTC, Naatan requested changes
This feels a little error prone. Basically we have two cases state push addresses:

- I'm pushing a change to an existing project
- I'm pushing to an all-new project

The changes here are addressing the second use-case, but implicitly. Meaning it's not clear from the code that this is why it's what it is doing. I also feel like assuming "branch doesn't exist means use the default" is error-prone for the first use-case.

I think the real issue here might be that when we create the project we create it with the default branch, rather than the one that was requested.

2021-11-18 18:11 UTC, MDrakos commented on test/integration/pull_int_test.go
> -	cp.ExpectExitCode(1)
I'm not sure how this worked before... we've just pushed and it worked, we push again and expect it to fail?

2021-11-18 19:13 UTC, Naatan approved these changes

2021-11-18 19:25 UTC, merged