Improve service uniqueness and management
ActiveState/cli pull request #1744
Opened 2022-03-09 21:22 UTC by daved

2022-03-31 18:11 UTC, Naatan requested changes
Don't have time to finish reviewing right now, so I'll submit what I have so you have something to action on.

If finished addressing these comments; please do a self-review and add LOTS of comments. I consider most of this logic to be not self-evident, due to its low level nature, and as a result we should be doing our best to convey through comments what the code is doing.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/internal/flisten/flisten.go
> +	namespaceDir := filepath.Dir(namespace)
This feels error prone, `namespace` does not convey "filepath" to me. Suggest making that an explicit trait of the namespace or renaming namespace.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/internal/flisten/flisten.go
> +package flisten
`flisten` is not self-explanatory. Please either rename or add some inline documentation explaining what its responsibilities are.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +type MatchedHandler func(input string) (resp string, isMatched bool)
Can we add some docs here explaining what this does and why it does it?

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +		ctx, cancel := context.WithTimeout(ipc.ctx, time.Second*3)
Please add a comment explaining why we're handling `ErrInUse` the way we are.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +		}
Please add comment explaining why `ErrConnRefused` leads to us cleaning up and starting again. I assume this is basically asserting that the process was shut down uncleanly?

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +					fmt.Fprintln(os.Stderr, fmt.Errorf("listen and server: %w", err)) // TODO: something more useful, log properly, at least
Seems like a todo worth actioning. Also no todo's in code please. File jira tickets.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +	ipc.wg.Add(1)
Please add comments explaining what's happening here.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +			if err := accept(ipc.ctx, conns, listener); err != nil {
Please add comments explaining what's happening here.

2022-03-31 18:11 UTC, Naatan commented on internal/ipc/ipc.go
> +		if err := routeToHandler(ipc.ctx, ipc.wg, conns, ipc.mhs); err != nil {
Please add comments explaining what's happening here.

2022-03-31 23:26 UTC, Naatan requested changes

2022-03-31 23:26 UTC, Naatan commented on internal/ipc/ipc.go
> +		if err := routeToHandler(ipc.ctx, ipc.wg, conns, ipc.mhs); err != nil {
Also call out what this is doing with `conns` in particular.

2022-03-31 23:26 UTC, Naatan commented on internal/svcctl/comm.go
> +	g Getter
Words

2022-03-31 23:26 UTC, Naatan commented on internal/svcctl/comm.go
> +	Get(ctx context.Context, key string) (value string, err error)
To be consistent with the other changes we should also call these `Request`.

2022-03-31 23:26 UTC, Naatan commented on internal/svcctl/svcctl.go
> +func waitdn(ctx context.Context, c IPCommunicator) error {
w -- down, not dn

2022-04-01 20:28 UTC, daved commented on internal/ipc/client.go
> +	return time.Since(start), nil
I based this on the *nix `ping` which reports timing. I'd like to keep it if you're willing.

2022-04-05 19:27 UTC, Naatan requested changes
Looking good! Just one minor nitpicky change.

2022-04-05 19:27 UTC, Naatan commented on cmd/state-svc/main.go
> +	if _, err := svcctl.DefaultEnsureStartedAndLocateHTTP(); err != nil {
I don't understand what `Default` is meant to convey here? I'd prefer we suffix the non-default rather than prefix the default.

2022-04-05 19:51 UTC, Naatan approved these changes

2022-04-05 20:50 UTC, merged