Fixed multi-add of the same bin path in ENV["PATH"] when more than on…
ActiveState/cli pull request #1766
Opened 2022-03-22 16:32 UTC by mitchell-as

…e exclusion path is present.

2022-03-22 22:52 UTC, MDrakos requested changes

2022-03-22 22:52 UTC, MDrakos commented on pkg/platform/runtime/envdef/environment.go
> +		include_path := true
The Go convention is camel case.

2022-03-23 15:06 UTC, mitchell-as commented on pkg/platform/runtime/envdef/environment.go
> +		include_path := true
Whoops, sorry about that.

2022-03-23 15:45 UTC, MDrakos approved these changes

2022-03-23 17:46 UTC, merged