Fix windows PATH on uninstall
ActiveState/cli pull request #1813
Opened 2022-04-19 19:44 UTC by MDrakos

2022-04-19 20:43 UTC, MDrakos commented
The failing integration tests need #1814 to be pass

2022-04-20 17:14 UTC, Naatan requested changes

2022-04-20 17:14 UTC, Naatan commented on internal/runners/clean/run_win.go
> +	_, err = exeutils.ExecuteAndForget(subshell.DetectShellBinary(cfg), args)
Should revert this. The flags are specifically for cmd.exe. And the issue of not finding cmd.exe on path was a symptom, not the problem we're fixing.

2022-04-20 21:07 UTC, Naatan submitted a review, later dismissed

2022-04-27 19:53 UTC, Naatan approved these changes

2022-04-27 20:06 UTC, merged