Removed reporting of MachineID to Google Analytics.
ActiveState/cli pull request #1820
Opened 2022-04-22 18:02 UTC by mitchell-as

It was replaced by DeviceID.

2022-04-25 19:53 UTC, Naatan requested changes
We should be able to drop the machineid package.

2022-04-25 21:11 UTC, mitchell-as commented
I tried, but we are using it in other places unrelated to analytics, for example https://github.com/ActiveState/cli/blob/9fe4c6c6143a1d4b21e3c9c399545362bfa0815c/pkg/platform/model/vcs.go#L386 and https://github.com/ActiveState/cli/blob/9fe4c6c6143a1d4b21e3c9c399545362bfa0815c/pkg/platform/authentication/auth.go#L364

2022-04-27 19:50 UTC, Naatan requested changes

2022-04-27 19:50 UTC, Naatan commented on internal/rollbar/rollbar.go
> +	custom["MachineID"] = uniqid.Text()
```suggestion
	custom["DeviceID"] = uniqid.Text()
```

2022-04-27 19:50 UTC, Naatan commented on pkg/platform/model/vcs.go
> +		AnonID:         uniqid.Text(),
```suggestion
```

2022-04-28 17:14 UTC, Naatan approved these changes

2022-04-28 17:14 UTC, merged