Rework IPC server graceful shutdown
ActiveState/cli pull request #1857
Opened 2022-05-11 20:07 UTC by daved

2022-05-13 20:52 UTC, daved commented
@Naatan This PR:

1. introduces a couple helper types to debug the TCP client/server interactions using slowed request/response behavior
2. converts a Bash IPC shutdown test script to Go code
3. reduces the IPC server client-connection code
4. resolves shutdown errors by rechecking svc stop status for certain errors (EOF, reset by peer, and broken pipe)

I imagine you might want to strip out some of this troubleshooting/debugging code, but I value it enough to leave it in and wait for your word before pruning it.

2022-05-16 17:05 UTC, Naatan requested changes

2022-05-16 17:05 UTC, Naatan commented on internal/ipc/internal/flisten/flisten.go
> +		debug:    os.Getenv("FLISTEN_DEBUG") != "",
```suggestion
		debug:    os.Getenv("FLISTEN_DEBUG") == "true",
```

2022-05-16 21:32 UTC, daved commented on internal/svcctl/svcctl.go
> +				return locale.WrapError(err, "svcctl_ping_failed", "Ping encountered unexpected failure: {{.V0}}", err.Error())
I'm fairly sure we're not expecting this case. If it happens, we'll want to know what error it is since it doesn't fit within the current handling.

2022-05-16 22:32 UTC, Naatan commented on internal/svcctl/svcctl.go
> +				return locale.WrapError(err, "svcctl_ping_failed", "Ping encountered unexpected failure: {{.V0}}", err.Error())
So do the changes you make fix the case in which EOF errors were happening? Cause it was happening reliably on CI. Seems to me that if that is still prone to happen then we should handle it gracefully.

2022-05-17 21:57 UTC, Naatan requested changes
Just setting this to request changes since you are addressing some new feedback I gave via Slack.

Namely supporting the following error condition:

```
          Could not stop serviceManager: Cannot stop service: Waiting for service shutdown
           confirmation failed: Ping encountered unexpected failure: Failed to complete pi
          ng request: Failed to complete ping request: Failed to read from server connecti
          on: read unix @->C:\Users\RUNNER~1\AppData\Local\Temp\state-ipc\state-DX-925.soc
          k: wsarecv: An existing connection was forcibly closed by the remote host.: wsar
          ecv: An existing connection was forcibly closed by the remote host.: An existing
           connection was forcibly closed by the remote host.   
```

2022-05-18 23:12 UTC, daved commented on internal/svcctl/svcctl.go
> +				return locale.WrapError(err, "svcctl_ping_failed", "Ping encountered unexpected failure: {{.V0}}", err.Error())
It is treated as a "TempNotUp" error, so waitDown will try to fully confirm shutdown.

2022-05-24 15:50 UTC, Naatan approved these changes

2022-05-25 21:04 UTC, merged