Fixed potential segfault in secrets get with no project file present.
ActiveState/cli pull request #1859
Opened 2022-05-16 17:14 UTC by mitchell-as

2022-05-16 22:33 UTC, MDrakos requested changes
The `project` struct is just a `projectfile` with an `outputter`. If we are creating a `project` without a `projectfile` somewhere we should find out where and fix that... unless there is a legitimate case for it, but I can't think of one at the moment.

2022-05-16 22:48 UTC, Naatan commented
@MDrakos @mitchell-as We just pass the project in that was detected at runtime. It being nil is a legitimate use-case we should be addressing. The current fix seems appropriate to me.

2022-05-16 22:59 UTC, MDrakos commented
> @MDrakos @mitchell-as We just pass the project in that was detected at runtime. It being nil is a legitimate use-case we should be addressing. The current fix seems appropriate to me.

@Naatan If no project was detected then shouldn't that project struct be nil? Why is it not nil but the underlying projectfile is?

2022-05-16 23:01 UTC, Naatan commented
> > @MDrakos @mitchell-as We just pass the project in that was detected at runtime. It being nil is a legitimate use-case we should be addressing. The current fix seems appropriate to me.
> 
> @Naatan If no project was detected then shouldn't that project struct be nil? Why is it not nil but the underlying projectfile is?

You're totally right. Ignore everything I said.

2022-05-17 20:10 UTC, MDrakos approved these changes

2022-05-17 20:15 UTC, merged