Add reporting of cli args of caller that starts svc
ActiveState/cli pull request #1996
Opened 2022-08-04 01:50 UTC by daved

2022-08-08 17:43 UTC, Naatan requested changes
Can we also improve the error of `flisten in use` so that it conveys that this error is partly expected? Otherwise this will continue to look like something that needs fixing.

2022-08-08 17:43 UTC, Naatan commented on cmd/state-svc/main.go
> +					Description: "Argument text of caller",
The description should answer the question "Why should I provide this?".

2022-08-09 17:26 UTC, Naatan requested changes
You missed this comment I think: https://github.com/ActiveState/cli/pull/1996#pullrequestreview-1065554573

2022-08-09 19:34 UTC, daved commented
@Naatan Sorry about missing that. I also added a test.

2022-08-11 17:07 UTC, Naatan requested changes

2022-08-11 17:07 UTC, Naatan commented on cmd/state-svc/service.go
> +			return errors.New("An existing server instance appears to be in use")
This should still wrap imo.

2022-08-15 17:31 UTC, Naatan approved these changes

2022-08-15 17:40 UTC, merged