Do not allow deploying in the root directory.
ActiveState/cli pull request #2168
Opened 2022-10-19 21:37 UTC by mitchell-as

2022-10-19 23:53 UTC, MDrakos approved these changes
Looks fine to me but you may want to get Nathan and/or Pete to take a look at the error message

2022-10-20 20:45 UTC, Naatan requested changes
The person encountering the bug did not seem to have ran deploy with a custom target path, meaning that something in our implementation defaulted to the root. I suspect this might be a case of the `HOME` env var not being set, but worth digging into that.

2022-10-20 20:51 UTC, mitchell-as commented
@Naatan This is what happens in the docker file mentioned in the ticket. The command is run at root (/) so the deployment path was '.', which is root (/).

2022-10-20 21:09 UTC, Naatan commented
@mitchell-as I see.. in that case can we just move the logic to here:

https://github.com/ActiveState/cli/blob/6adb01cf7a668ad1797e35108ea24b1b5e0794de/pkg/platform/runtime/setup/setup.go#L166-L166

That way it'll apply to all runtime usage. I don't think we're ever going to want to install to root.

2022-10-20 21:11 UTC, Naatan commented
Also I think we need to resolve the path, as right now we wouldn't catch something like `/` or `../` from `/opt`.

2022-10-20 21:28 UTC, mitchell-as commented
We are resolving it. `NewCustomTarget()` is calling `fileutils.ResolveUniqPath()`, which does what you are expecting. That is why I was comfortable with `== "/"`.

2022-10-20 22:15 UTC, mitchell-as commented
Okay, moved the check into setup. Not sure about the wording though. Feel free to suggest something better.

2022-10-20 22:18 UTC, Naatan requested changes

2022-10-20 22:18 UTC, Naatan commented on pkg/platform/runtime/setup/setup.go
> +		return locale.NewInputError("err_runtime_setup_root", "Cannot set up a runtime in the root directory. Please try in another directory.")
```suggestion
		return locale.NewInputError("err_runtime_setup_root", "Cannot set up a runtime in the root directory. Please specify or run from a user-writable directory.")
```

2022-10-21 18:16 UTC, Naatan approved these changes

2022-10-21 18:17 UTC, merged