Do not forward io.Writer errors to Rollbar.
ActiveState/cli pull request #2169
Opened 2022-10-19 22:01 UTC by mitchell-as

2022-10-24 19:58 UTC, daved submitted a review, later dismissed

2022-10-24 20:13 UTC, mitchell-as commented
Upon further review this is not correct, because io.Writer is an interface and we cannot make any assuptions about an error coming from `io.Writer.Write()`.

2022-10-28 19:22 UTC, mitchell-as commented
Upon re-review of this ticket's ACs, I'm going with the "when all else fails, silence the error" part. This particular error is a Windows I/O error 232: ERROR_NO_DATA. I don't know if it's worth specifically handling this case, as it becomes a slippery slop of what types of I/O errors to handle, and if we handle it here, should we be handling these types of io.Writer.Write() errors elsewhere in the codebase?

2022-10-28 19:27 UTC, Naatan requested changes
Did you check the first AC? 

> Ensure that our code for detecting whether colored output is supported is working as expected

It seems that the issue might stem from us never passing `true` for `checkTerminal`:

https://github.com/ActiveState/cli/blob/3a08029a3f8fcfecd3e89d5d2b18b86a1e394935/cmd/state/output.go#L33-L33

eg.

https://github.com/ActiveState/cli/blob/3a08029a3f8fcfecd3e89d5d2b18b86a1e394935/cmd/state/output.go#L58-L58

https://github.com/ActiveState/cli/blob/3a08029a3f8fcfecd3e89d5d2b18b86a1e394935/cmd/state/output.go#L76-L76

I think passing `true` here might address the issue.

2022-10-28 19:56 UTC, mitchell-as commented
Yes I did. I've been running the state tool a lot in Git Bash on Windows (which doesn't have color support) and have not run into anything weird. I *suppose* it is possible that a color escape sequence could be interpreted as an EOF sequence, so I've made a change to not always assume color is available on Windows, but I am not confident that this is the solution to the rollbar bug.

2022-10-28 20:14 UTC, Naatan commented
> Yes I did. I've been running the state tool a lot in Git Bash on Windows (which doesn't have color support) and have not run into anything weird. I _suppose_ it is possible that a color escape sequence could be interpreted as an EOF sequence, so I've made a change to not always assume color is available on Windows, but I am not confident that this is the solution to the rollbar bug.

I see. Do you think it makes sense to include the changes I suggested? It still seems relevant to me.

2022-10-28 20:20 UTC, mitchell-as commented
`checkTerminal` is `true` by default: https://github.com/ActiveState/cli/blob/3a08029a3f8fcfecd3e89d5d2b18b86a1e394935/cmd/state/output.go#L31, so `terminal.StdoutSupportsColors()` was always being called, hence my downstream change to not always return `true` for Windows.

2022-10-28 20:22 UTC, Naatan commented
Oh I see, I had it inverted. Ok makes sense then, thanks for explaining!

2022-10-28 20:22 UTC, Naatan approved these changes

2022-10-28 20:23 UTC, merged