Make "access is denied" installer errors input errors.
ActiveState/cli pull request #2196
Opened 2022-10-28 15:02 UTC by mitchell-as

They should not be logged to rollbar.

2022-10-28 23:43 UTC, daved approved these changes

2022-10-31 18:08 UTC, Naatan requested changes
Looks good! But can we move `isAccessDeniedError` to osutils and make it public? Seems useful!

2022-10-31 18:54 UTC, daved commented on internal/installmgr/stop_unix.go
> +	return false
I threw together a little program and got this:
```
package main

import (
        "errors"
        "fmt"
        "os"
        "os/exec"
        "syscall"

        "github.com/shirou/gopsutil/v3/process"
)

func main() {
        procs, err := process.Processes()
        if err != nil {
                fmt.Fprintln(os.Stderr, err)
                return
        }

        for _, p := range procs {
                name, err := p.Name()
                if err != nil {
                        fmt.Fprintln(os.Stderr, err)
                        continue
                }

                if os.Args[1] == name {
                        fmt.Printf("found process named %q: attempting kill\n", name)
                        if err := killProcess(p, name); err != nil {
                                if eerr := (&exec.ExitError{}); errors.As(err, &eerr) {
                                        fmt.Fprintf(os.Stderr, "xx :%s\n", string(eerr.Stderr))
                                }
                                fmt.Fprintln(os.Stderr, err)
                        }
                }
        }
}

func killProcess(proc *process.Process, name string) error {
        children, err := proc.Children()
        if err == nil {
                for _, c := range children {
                        if err = c.Kill(); err != nil {
                                if isAccessDeniedError(err) {
                                        fmt.Println("denied child kill")
                                }
                                return err
                        }
                }
        }

        if err = proc.Kill(); err != nil {
                if isAccessDeniedError(err) {
                        fmt.Println("denied proc kill")
                }
                return err
        }

        return nil
}

func isAccessDeniedError(err error) bool {
        errno, ok := err.(syscall.Errno)
        return ok && errno == syscall.EPERM
}
```
I then ran `sudo less ~/.bashrc` in a separate terminal, and the error is detected as "access denied". If, instead, I run `less ~/.bashrc`, the application succeeds in killing the less instance.

2022-11-02 16:19 UTC, mitchell-as commented on internal/installmgr/stop_unix.go
> +	return false
Thanks, this was helpful!

2022-11-02 16:55 UTC, Naatan approved these changes

2022-11-02 16:56 UTC, merged