Always show either "Installing Runtime" or "Updating Runtime" when installing or updating a runtime
ActiveState/cli pull request #2242
Opened 2022-11-15 22:53 UTC by mitchell-as

Explicit calls to `runbits.RefreshRuntime()` work when we know a runtime update needs to happen. This function would display "Installing Runtime" or "Updating Runtime" to the user. However, implicit updates (e.g. after `state update`) would not call this function, and a silent runtime update would occur.

This PR adds a new event to the runtime that can be used to always print either "Installing Runtime" or "Updating Runtime" to the user when installing or updating a runtime, regardless of whether it's an explicit update or implicit update.

2022-11-16 18:54 UTC, MDrakos approved these changes
Nice work! This makes sense to me.

2022-11-17 18:00 UTC, Naatan requested changes
This feels like overkill for what we're looking for. It's a lot of added complexity for what amounts to a simple message meant to indicate that we are sourcing their runtime.

I think this PR can just be a single addition here:

https://github.com/ActiveState/cli/blob/9b010694dfeca42fc68750ea9c3e0aebbd506985/internal/runbits/progressbar/progressbar.go#L104-L104

That prints something like "Setting up runtime". Making the distinction between install and update is nice if we can assert this, but doesn't warrant the added complexity just for this message imo.

2022-11-17 19:27 UTC, mitchell-as commented
Okay, how about this? BuildStarted does not always fire, but SolverStart seems to.

2022-11-17 19:29 UTC, Naatan approved these changes

2022-11-17 19:31 UTC, merged