Add trigger token for executor usage
ActiveState/cli pull request #2391
Opened 2023-02-23 03:38 UTC by daved

2023-02-23 03:41 UTC, daved commented
@Naatan In the AC, the `state exec` command is to get a new token as "exec-cmd". However this would then not match with other commands like activate which do not use that suffix. I added a new token for executors simply names "executor". I'm happy to redo this to match AC more exactly if the odd "-cmd" suffix is desirable, or the new token can be renamed to be more distinct from the existing "exec" token.

2023-02-23 18:22 UTC, Naatan requested changes
Please stick to the original AC's. I agree the naming inconsistency is awkward, but ultimately inconsequential and it's better than having DW have to handle runtime tracking using a different trigger for some version or date cutoff.

I'm always happy to chat on Slack if AC's are posing problems. Rather we have a quick chat and adjust the AC's before investing time on implementation.

2023-02-24 17:44 UTC, Naatan requested changes

2023-02-24 17:44 UTC, Naatan commented on pkg/platform/runtime/target/target.go
> +		strings.HasPrefix(trigger, triggerExecPrefix)
This logic seems to only cover the `state exec` command.. so we shouldn't address executors here.

2023-02-28 18:11 UTC, Naatan approved these changes

2023-03-01 18:49 UTC, merged