Always delete the branch name directory on Windows.
ActiveState/cli pull request #2401
Opened 2023-02-28 18:27 UTC by mitchell-as

It does not contain the config directory.

2023-02-28 19:34 UTC, mitchell-as commented
It feels a bit icky, but I'm not sure how best to go about reconciling the differences between installation structure on Windows vs Linux/macOS. Let me know if you have any ideas. Otherwise, we can go with something like this.

2023-02-28 22:12 UTC, mitchell-as commented
Never mind. After talking to Nathan about this, I'm going to try something else. All three platforms use the same install structure for integration tests. Windows is doing something different.

2023-03-01 16:35 UTC, MDrakos requested changes
This fixes our integration tests CI issues but could legitimately mess with users attempting to uninstall the state tool as part of their CI steps... can we use `condition.InTest` instead?

2023-03-01 16:55 UTC, MDrakos approved these changes

2023-03-01 16:56 UTC, merged