Log autoupdate failures instead of halting execution.
ActiveState/cli pull request #2418
Opened 2023-03-08 15:10 UTC by mitchell-as

2023-03-08 16:31 UTC, MDrakos requested changes
I don't believe the `autoUpdate` function will notify the user that the auto-update failed. Rather than this failing silently maybe we should provide a message to the user that their auto-update failed and remind them that they can run `state update` to try again. You may want to contact Pete and/or Nathan for copy.

2023-03-08 21:00 UTC, Naatan approved these changes

2023-03-08 22:39 UTC, mitchell-as commented
@MDrakos I got an OK from Nathan and GitHub won't let me merge without your approval.

2023-03-09 00:14 UTC, MDrakos approved these changes

2023-03-09 14:35 UTC, merged