Enable PYTHONUTF8 in Git Bash on Windows for default Python projects.
ActiveState/cli pull request #2440
Opened 2023-03-20 20:17 UTC by mitchell-as

Python cannot detect a UTF-8 environment within a Git Bash terminal, so the UTF-8 characters in the activation message cannot be printed by Python. Provide a hint.

2023-03-21 22:57 UTC, daved submitted a review, later dismissed

2023-03-22 18:15 UTC, Naatan requested changes
We discussed this during stand and agreed that a more appropriate solution would be to try and remove the UTF8 dependency from the script.

The perspective there being that this yaml code is meant to be an onboarding experience. And so us having additional chunks of code in there to work around bugs or facilitate advanced use-cases would detract from that experience.

2023-03-22 20:58 UTC, Naatan approved these changes

2023-03-22 20:58 UTC, Naatan requested changes
Oh.. I think we can drop this? 

https://github.com/ActiveState/cli/pull/2440/files#diff-d578f534a6a7c90608b33507b2fe2531d46837a66000f77e834781b1f6da3088L5

2023-03-22 21:01 UTC, mitchell-as commented
Yep, you're right.

2023-03-22 21:12 UTC, merged