Stream file uploads.
ActiveState/cli pull request #2594
Opened 2023-06-20 20:59 UTC by mitchell-as

2023-06-20 21:51 UTC, mitchell-as commented
This seems to work, but it'll be more comfortable when the integration tests are available.

2023-06-21 17:21 UTC, Naatan requested changes

2023-06-21 17:21 UTC, Naatan commented on internal/gqlclient/gqlclient.go
> +	bodyReader, body := io.Pipe()
nit: Can we call the second one bodyWriter?

2023-06-21 17:21 UTC, Naatan commented on internal/gqlclient/gqlclient.go
> +			return
These errors should not be dropped. I suggest utilizing a channel to catch them. You'd have to refactor the code such that the actual request happens within the scope of this function, as sharing channels between functions always ends up a bit messy.

Currently this happens here:

https://github.com/ActiveState/cli/blob/47e6eef1a732a2dc5ef32927952fe98d98055452/internal/gqlclient/gqlclient.go#L194-L194

I suggest moving the request logic to this function, and keeping the linked one just for handling the response.

2023-06-21 20:07 UTC, mitchell-as commented on internal/gqlclient/gqlclient.go
> +			return
I changed the `createMultiPartUploadRequest()` function to return an error channel that can be checked immediately and from within `runRaw()` after submitting the graphql request. It seems to work okay, but let me know if I missed something.

2023-06-21 20:11 UTC, Naatan commented on internal/gqlclient/gqlclient.go
> +			return
Sorry but that's what I was warning; sharing channels between functions always ends up being messy. Much of this code was proof of concept grade, so we're not beholden to the architecture, refactoring the code such that we don't share channels between functions feels reasonable.

2023-06-21 20:12 UTC, Naatan requested changes
https://github.com/ActiveState/cli/pull/2594#discussion_r1237627653

2023-06-21 20:20 UTC, mitchell-as commented on internal/gqlclient/gqlclient.go
> +			return
Okay, next time please word your request more forcefully. I took it to be a suggestion/recommendation, especially because we do this sort of thing (error channel passing) in runtime setup.

2023-06-21 20:51 UTC, mitchell-as commented
Okay, I think I made the changes you originally hoped to see. If not, let me know.

2023-06-21 21:26 UTC, Naatan requested changes
Looking good, just one minor change.

2023-06-21 21:26 UTC, Naatan commented on internal/gqlclient/gqlclient.go
> +		return errs.Wrap(err, "Could not marshal vars")
Please move this above the goroutine, cause otherwise if and when this triggers the goroutine would be left dangling.

2023-06-22 16:03 UTC, Naatan approved these changes

2023-06-22 16:30 UTC, merged