Added integration test for verifying headers sent to the Platform.
ActiveState/cli pull request #2636
Opened 2023-07-18 18:01 UTC by mitchell-as

<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-1836" title="DX-1836" target="_blank"><img alt="Task" src="https://activestatef.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />DX-1836</a>  We have an integration test for platform request headers
  </td></table>
  <br />

2023-07-18 21:09 UTC, mitchell-as commented
If this PR is accepted, it will need to be force-merged unless DX-2013 is solved before I'm back next week.

2023-07-25 16:30 UTC, Naatan requested changes

2023-07-25 16:30 UTC, Naatan commented on pkg/platform/api/api.go
> +		logging.Debug("X-Requestor: %s\n", resp.Request.Header.Get("X-Requestor"))
Please also add the URL (put it first).

2023-07-25 16:30 UTC, Naatan commented on internal/constants/constants.go
> +const PlatformApiRequestPrintHeadersEnvVarName = "ACTIVESTATE_CLI_PLATFORM_API_REQUEST_PRINT_HEADERS"
```suggestion
// PlatformApiRequestPrintRequestsEnvVarName is only used for an integration test to print some
// expected headers from a Platform API request.
const PlatformApiRequestPrintRequestsEnvVarName = "ACTIVESTATE_CLI_PLATFORM_API_REQUEST_PRINT_REQUESTS
```

2023-07-25 17:03 UTC, Naatan approved these changes

2023-07-25 17:11 UTC, mitchell-as commented
@Naatan would you please force-merge this? The failing unit tests do not belong to this ticket and Target & Verify is still failing.

2023-07-25 17:12 UTC, merged