Treat BuildPlanner errors are input errors
ActiveState/cli pull request #2637
Opened 2023-07-18 20:26 UTC by MDrakos

This PR adds back the `Wrapped` field to the `BuildPlanError` type. When we report errors we unwrap the error and check to see if any of the underlying errors are input errors, if they are we do not report.

This is only added when we encounter a planning error as other errors before this occur when a commit or project could not be found.

2023-07-18 21:21 UTC, Naatan requested changes
@MDrakos does this mean that any buildplan error will always just say "The Platform failed to plan the build for this project."?

The intend of the story is to not have it report to rollbar. Not to change the error message. We should still be able to give an error message that is actionable.

2023-07-18 22:51 UTC, MDrakos commented
@Naatan good point. I think this latest change addresses your concerns.

2023-07-18 23:42 UTC, Naatan requested changes

2023-07-18 23:42 UTC, Naatan commented on pkg/platform/model/buildplanner.go
> +			Wrapped:          locale.NewInputError("err_buildplanner"),
Looks like you can drop this?

2023-07-19 16:02 UTC, Naatan approved these changes

2023-07-19 17:12 UTC, merged