Update Build Expression parser for forward compatibility
ActiveState/cli pull request #2709
Opened 2023-08-15 21:30 UTC by MDrakos

2023-08-16 15:16 UTC, mitchell-as requested changes
Overall I like what you've done here. There are a few improvements I think you can make though.

2023-08-17 16:59 UTC, MDrakos commented on pkg/platform/runtime/buildexpression/buildexpression.go
> +	Values []*Value
A slice is already a pointer so if the request for this change is so we can do a `nil` check that's already the case. I like the renaming though! I think that's what I originally had but then changed it for some reason 🤔

2023-08-17 16:59 UTC, MDrakos commented on pkg/platform/runtime/buildexpression/buildexpression.go
> +		if a.Assignment.Name == "" && a.Assignment.Name != "runtime" {
Whoops should be an `or`

2023-08-17 16:59 UTC, MDrakos commented on pkg/platform/runtime/buildexpression/buildexpression.go
> +		if a.Value.Ap.Name == "" && a.Value.Ap.Name != "runtime" {
Same here

2023-08-17 18:53 UTC, MDrakos commented on pkg/platform/runtime/buildexpression/buildexpression.go
> +}
Good point!

2023-08-17 20:20 UTC, mitchell-as commented on pkg/platform/runtime/buildexpression/buildexpression.go
> +	Values []*Value
I...did not know that. Thanks for making me question an assumption I was making.

2023-08-17 20:31 UTC, mitchell-as approved these changes
Nicely done.

2023-08-17 23:04 UTC, Naatan approved these changes
I see no real architectural changes here, so I'll defer to Mitchell's review.

2023-08-17 23:09 UTC, merged