Update runtime-debug error handling
ActiveState/cli pull request #2737
Opened 2023-08-25 20:56 UTC by MDrakos

2023-08-29 17:00 UTC, Naatan requested changes

2023-08-29 20:08 UTC, MDrakos commented on pkg/platform/api/buildplanner/model/buildplan.go
> +	}
This change also introduces the `Err` field: https://github.com/ActiveState/cli/pull/2737/files#diff-14612946db10f18744a68890b9e353cf87d4da9104592d9fe4346264ed83ef77R95

2023-08-30 17:03 UTC, Naatan commented on pkg/platform/api/buildplanner/model/buildplan.go
> +	}
I get that, but that doesn't do anything to let us identify the error type, which is what this story is about. I'm not against also including this change, I just want to understand what this change does? What type of scenario are we not handling prior to this change?

2023-08-30 17:05 UTC, Naatan approved these changes
LGTM. I don't have any issue with the change I'm still commenting on other than wanting to understand what error conditions this would raise.

2023-08-30 20:18 UTC, MDrakos commented on pkg/platform/api/buildplanner/model/buildplan.go
> +	}
We are already identifying build planner errors but this has only been solving errors. Adding the error field and returning it first allows us to also capture other errors that we want to be considered as build planner errors. In this PR I've included deprecation and fallback errors when processing a build planner response to this type so they will also be identified as build planner errors.

2023-08-30 23:16 UTC, merged