Enrich service wait up/down errors with more debug info.
ActiveState/cli pull request #2740
Opened 2023-08-30 20:51 UTC by mitchell-as

This should help with rollbar reports.

2023-08-30 22:11 UTC, daved reviewed
@Naatan For this story, I agree that we should step back from the wait up/down pacing (new story filed here: https://activestatef.atlassian.net/browse/DX-2176), but I'm curious to bring up the third point in the AC:
> Consider and possibly include having some flag or arg passed in to the service start call at system startup so that we can better understand the context of the reported errors.

I feel fairly strongly that this would be an exceedingly useful data point. However, we didn't discuss a design. If you agree, should we create a separate story or update the current one?

2023-08-30 22:21 UTC, Naatan commented
Could you guys please add your concerns with the ACs to the jira ticket and move it back to triage.

We should not be omitting AC's without conversation with either myself or Pete.

I have opinions, but need more context. Probably easier if we talk about this during stand.

2023-08-31 19:56 UTC, daved requested changes

2023-08-31 19:56 UTC, daved commented on cmd/state-svc/main.go
> +				{Name: "startup", Value: &startup}, // differentiate between autostart and cli invocation
I'm not sure if we have curated the help output for the service, but I suggest setting Hidden to true.

2023-08-31 19:56 UTC, daved commented on cmd/state-svc/main.go
> +					argText = "svc-start:startup"
```suggestion
					argText += "-atstart"
```

2023-08-31 20:00 UTC, daved requested changes

2023-08-31 20:00 UTC, daved commented on cmd/state-svc/autostart/autostart.go
> +	Args:           []string{"start", "--startup"},
```suggestion
	Args:           []string{"start", "--autostart"},
```

2023-08-31 20:00 UTC, daved commented on cmd/state-svc/main.go
> +				{Name: "startup", Value: &startup}, // differentiate between autostart and cli invocation
I suggest renaming "startup" to autostart.

2023-08-31 20:14 UTC, daved approved these changes

2023-08-31 21:09 UTC, Naatan requested changes

2023-08-31 21:09 UTC, Naatan commented on cmd/state-svc/main.go
> +					argText += "-autostart"
```suggestion
					argText += "svc-start:auto"
```

2023-08-31 21:15 UTC, Naatan approved these changes

2023-08-31 21:46 UTC, merged