Attempt to trap "flisten in use" errors on CI for further debugging.
ActiveState/cli pull request #2756
Opened 2023-09-15 19:25 UTC by mitchell-as

2023-09-15 20:32 UTC, mitchell-as commented
Hopefully this is what you had in mind.

2023-09-15 21:49 UTC, Naatan requested changes
Looks ok in terms of logic, but this is repurposing `DetectLogErrors()`, I was suggesting you use it as a reference.

Also we would need to then invoke this on each integration test on the suite shutdown behaviour, eg. add a `TearDownSuite()` method to:

https://github.com/ActiveState/cli/blob/ee9362557236638590111294a388f3a95063d1d3/internal/testhelpers/tagsuite/tagsuite.go#L88-L88

The end result should be that we check for flisten errors on each integration test that uses the suite. `DetectLogErrors()` itself should be unchanged, it's just for reference.

2023-09-18 16:29 UTC, mitchell-as commented
I see. `DetectLogErrors()` has a deceiving name then, as I thought it was already being used to catch silent test failures.

I couldn't add a `TearDown()` function to suites because sessions contain log files, so the check needs to occur on session close. Unless of course I'm missing something, which is entirely possible.

2023-09-18 18:12 UTC, Naatan approved these changes

2023-09-18 18:12 UTC, mitchell-as commented on internal/testhelpers/e2e/session.go
> +	require.NotContains(s.t, svcLogContents, "flisten in use", "Found flisten in use error in state-svc log file, contents:\n%s", svcLogContents)
I didn't realize that was a manual process. I thought if there was a suite/session error, logs would automatically be tacked on.

2023-09-18 18:12 UTC, merged