Remove `state auth signup --prompt`.
ActiveState/cli pull request #2762
Opened 2023-09-18 20:14 UTC by mitchell-as

Only signups via the browser are supported.

2023-09-18 22:55 UTC, mitchell-as commented
The auth integration test failure doesn't appear to be with these changes. It looks like only the most recent error is being shown to the user. I think it's related to https://activestatef.atlassian.net/browse/DX-2205

2023-09-19 19:57 UTC, Naatan requested changes

2023-09-19 19:57 UTC, Naatan commented on pkg/cmdlets/auth/login.go
> +				return errs.Wrap(err, "SignupWithBrowser failed")
Should just error out if we reach this. Launching the browser without context while in a prompt flow will just cause confusion.

2023-09-19 21:14 UTC, Naatan approved these changes

2023-09-19 21:18 UTC, merged