Turn off terminal echo while progressbar is present.
ActiveState/cli pull request #2768
Opened 2023-09-20 17:56 UTC by mitchell-as

2023-09-20 19:32 UTC, Naatan requested changes
This is really cool, definitely something I'd like to incorporate! However, this is for a bug, not for a story or task. Bugs should lead to fixes, not new enhancements.

It seems likely this cannot be fixed without an enhancement, so we should bring this back to triage to determine how better to address this.

I'd see this ultimately landing as part of the subshell package, or at least have it use the subshell package to determine the shell. We cannot rely on the SHELL environment variable alone.

2023-09-20 19:46 UTC, mitchell-as commented
I agree that it would be nice to somehow detect the current shell on Windows. On Linux and macOS it does not matter -- the POSIX APIs are the same and are independent of the running shell. However, I would like to point out that we tend to associated Git Bash with Bash on Windows, and that's a non-interactive shell. We probably won't be able to turn off echoing there, since it's not a true terminal with termios functionality. This may be the best we can do on Windows.

Anyway, punting back to triage as suggested.

2023-12-22 17:08 UTC, mitchell-as commented
Implemented in DX-2214 as a story.

2023-12-22 17:09 UTC, mitchell-as commented
Implemented in DX-2214 as a task.

2023-12-22 17:09 UTC, closed without merging