Drop vscode tests as we no longer publish the extension
ActiveState/cli pull request #2800
Opened 2023-10-06 21:00 UTC by Naatan

2023-10-09 14:37 UTC, mitchell-as commented
If the goal is to remove legacy VSCode support, then please also:

1. Remove https://github.com/ActiveState/cli/blob/8e2b6d23a93e4f2a18ea172e72f68d4668cbd845/cmd/state/internal/cmdtree/cmdtree.go#L282-L287
2. Address https://github.com/ActiveState/cli/blob/c260bb5c3eb7bbf44f19b5bd189b42f0b67f0198/cmd/state/main.go#L111-L120
3. Remove https://github.com/ActiveState/cli/blob/8e2b6d23a93e4f2a18ea172e72f68d4668cbd845/internal/testhelpers/tagsuite/tagsuite.go#L72

2023-10-09 14:37 UTC, mitchell-as requested changes
If the goal is to remove legacy VSCode support, then please also:

1. Remove https://github.com/ActiveState/cli/blob/8e2b6d23a93e4f2a18ea172e72f68d4668cbd845/cmd/state/internal/cmdtree/cmdtree.go#L282-L287
2. Address https://github.com/ActiveState/cli/blob/c260bb5c3eb7bbf44f19b5bd189b42f0b67f0198/cmd/state/main.go#L111-L120
3. Remove https://github.com/ActiveState/cli/blob/8e2b6d23a93e4f2a18ea172e72f68d4668cbd845/internal/testhelpers/tagsuite/tagsuite.go#L72

2023-10-10 18:15 UTC, Naatan commented
@mitchell-as thanks for spotting! Since that is testing a flag that's still implemented I don't feel comfortable dropping it for this PR, but I filed this followup story:

https://activestatef.atlassian.net/browse/DX-2262

I've dropped the vscode tag.

2023-10-10 18:17 UTC, mitchell-as approved these changes

2023-10-10 18:25 UTC, merged