Install scripts should always fetch and verify checksums.
ActiveState/cli pull request #2824
Opened 2023-10-17 17:10 UTC by mitchell-as

<table>
<td>
  <a href="https://activestatef.atlassian.net/browse/DX-2266" title="DX-2266" target="_blank"><img alt="Task" src="https://activestatef.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />DX-2266</a>  Install.ps1 and install.sh should ALWAYS verify the checksum
  </td></table>
  <br />

2023-10-17 18:05 UTC, mitchell-as commented
Test failures are not due to this PR. They are due to existing, known issues and the usual timeouts.

2023-10-17 18:36 UTC, Naatan requested changes

2023-10-17 19:00 UTC, mitchell-as commented on installers/install.ps1
> +} catch [System.Exception] {
Exceptions are output to stdout, so there's no need for additional work. I tested this and it's pretty clear what the issue is (e.g. network unreachable).

2023-10-18 16:28 UTC, Naatan approved these changes

2023-10-18 17:52 UTC, merged