Recognize headless errors on requirement operations
ActiveState/cli pull request #2876
Opened 2023-11-09 21:41 UTC by MDrakos

2023-11-09 23:04 UTC, MDrakos commented
Test failures are not due to the changes introduced in this PR

2023-11-10 15:12 UTC, mitchell-as requested changes

2023-11-10 15:12 UTC, mitchell-as commented on internal/runbits/rationalize/types.go
> +var ErrHeadless = errors.New("headless")
I view errors in this file as "global" errors. Is this going to be used outside the internal/runbits/requirements package? If not, we should put it in that package and remove it here.

2023-11-10 16:23 UTC, mitchell-as approved these changes
Changing to approved after further thought. This looks good to me.

2023-11-10 16:23 UTC, mitchell-as commented on internal/runbits/rationalize/types.go
> +var ErrHeadless = errors.New("headless")
Never mind, I think this will be used in user-facing errors for requirement operations like install/uninstall.

2023-11-10 17:16 UTC, merged