Fix failing integration tests
ActiveState/cli pull request #2993
Opened 2024-01-05 22:04 UTC by MDrakos

2024-01-05 22:44 UTC, Naatan requested changes
We disable the runtime because the test doesn't need them and is otherwise needlessly slowed down. If these tests were failing because of a missing runtime we should look into why they needed them, because for most of these I don't think they should actually need one.

2024-01-05 22:48 UTC, MDrakos commented
When we checkout or activate a runtime one of the events is to print out a message. This is done by invoking the `python` (or other language) executable. If we do not setup the runtime then this executable isn't available and the checkout will return with a non-zero exit code. The sandboxed environment does not have a system python on `PATH` which is likely why these tests were passed before and are not now.

2024-01-05 22:50 UTC, Naatan requested changes
Ok but the point still stands that these tests aren't testing the runtime and we want them to be performant. So whatever solution we come up with should still satisfy those conditions.

Two potential solutions perhaps:

- We could disable this message when this env var is set
- We could allow tests to explicitly pass in the system python for these kinds of cases

2024-01-06 00:02 UTC, MDrakos commented
Our integration tests are in a weird place between integration tests and end-to-end tests. The spirit of sandboxing was to give us a test environment that more accurately represents a system where the state tool would be run.

I would argue that disabling the runtime for the majority of the tests isn't what we want to do. We are sacrificing accuracy for convenience though this is more in line with an integration test rather than an end-to-end test. Further, by adding an event that uses the runtime, every test that activates or checks out a project indirectly tests the runtime.

That's just my two cents and in the end, I would rather continue down the road we are on. Just food for thought. I've gone with your first suggestion of disabling the events via an env var which is set by default in the test environment.

2024-01-08 17:03 UTC, Naatan commented
For tracking; filed followup for the performance issue here: https://activestatef.atlassian.net/browse/DX-2435

2024-01-08 18:02 UTC, Naatan requested changes

2024-01-08 18:02 UTC, Naatan commented on test/integration/run_int_test.go
>  	cp.Expect("Activated")
```suggestion
	cp.Expect("Activated", e2e.RuntimeSourcingTimeoutOpt)
```

2024-01-08 19:45 UTC, Naatan approved these changes

2024-01-08 21:58 UTC, merged