Attempt to merge the build script after creating a merge commit.
ActiveState/cli pull request #3186
Opened 2024-03-19 19:14 UTC by mitchell-as

2024-03-19 19:16 UTC, mitchell-as commented on internal/runners/pull/pull.go
> +	}
This change here may cause this ticket to be blocked on https://activestatef.atlassian.net/browse/DX-2619, where we want to do away with `buildscript.Sync()`.

2024-05-01 15:24 UTC, mitchell-as commented on version.txt
> +0.45.0-RC1
Needed to satisfy the "Check Format" action...

2024-05-01 16:02 UTC, Naatan requested changes
In addition to comments, as noted on Slack; please make the buildscript being dirty an error condition for `state pull`, do not try to resolve conflicts with an uncommitted buildscript.

2024-05-06 15:40 UTC, mitchell-as commented
After addressing PR review comments and merging remote changes, it looks like this whole thing was inadvertantly fixed in https://github.com/ActiveState/cli/pull/3249. I've updated the PR to just remove the unused code discovered during PR review.

2024-05-06 21:57 UTC, Naatan approved these changes

2024-05-07 21:18 UTC, mitchell-as commented
Please re-approve. I had to merge in v45's buildplan refactor as there was a conflict in this file related to file imports. I've resolve them here.

2024-05-07 21:25 UTC, Naatan approved these changes

2024-05-07 21:48 UTC, merged