Preserve `--ts now` from a previous commit when running `state uninstall`.
ActiveState/cli pull request #3223
Opened 2024-04-05 19:59 UTC by mitchell-as

2024-04-05 23:52 UTC, mitchell-as commented
Test failure is unrelated to this PR.

2024-04-05 23:53 UTC, Naatan requested changes
This looks ok to me, but during stand Mark said that he could repro by running the second install without `--ts`. Were you unable to repro this yourself?

2024-04-05 23:56 UTC, mitchell-as commented
Yeah, I ran

1. `state publish`
2. `state install --ts now`
3. `state uninstall`
4. `state install`

Step 4 was failing because the atTime in step 3 was reverting to a platform-defined timestamp, rather than the latest inventory timestamp from step 2. With the fix, step 3 preserves the latest inventory timestamp, as does step 4, which finds the newly published package.

2024-04-06 00:00 UTC, Naatan approved these changes

2024-04-06 00:13 UTC, merged