Check formatting on PRs
ActiveState/cli pull request #3239
Opened 2024-04-10 17:25 UTC by MDrakos

2024-04-11 18:40 UTC, Naatan requested changes
This looks good, but I worry this is going to cause a lot of maintenance overhead. There's a lot of unix/bash specific logic here that's prone to breakage as we've found with maintaining similar bash scripts.

Enforcing new lines is a pretty established best practice, there should be plenty of tools for us to use. 

Case in point: https://github.com/marketplace/actions/linelint

I'd suggest using something established and maintained rather than rolling our own.

2024-04-16 18:36 UTC, MDrakos commented
I looked at the action you linked as well as some other solutions. The main issue I can see is how we get these actions to only work with changed files. I don't believe `linelint` has a configuration option for this and it doesn't look like the repo has been touched in 2 years.

Other solutions have line linting as a feature but are also have a lot of other stuff we don't need which could lead to added headaches in getting them setup. Do we think we will want to add more linting in the future? If so I can see a case for us investing in a linting solution now.

This script is fairly simple, but does have the same issues that all other bash scripts have. For this use-case I think it makes sense but I'm happy to revisit other linting actions or give `linelint` a try.

2024-04-17 16:00 UTC, Naatan commented
Ok, let's go with this for now, if it turns into a maintenance overhead we should resort to a maintained solution sooner rather than later.

2024-04-17 16:06 UTC, Naatan approved these changes

2024-04-17 16:28 UTC, merged