Only show requested packages in change summary.
ActiveState/cli pull request #3341
Opened 2024-06-04 19:41 UTC by mitchell-as

2024-06-04 20:00 UTC, mitchell-as commented
The test failures are known and not due to this PR. This PR fixes the failing changesummary test: https://github.com/ActiveState/cli/actions/runs/9373208959/job/25806430933?pr=3341#step:27:705

2024-06-05 16:30 UTC, Naatan requested changes
Nice work! Just one minor change to reduce boilerplate.

2024-06-05 16:30 UTC, Naatan commented on internal/runbits/dependencies/changesummary.go
> +	}
```suggestion
	requested := newBuildPlan.RequestedArtifacts().ToIDMap()
```

2024-06-05 16:53 UTC, Naatan approved these changes

2024-06-05 17:02 UTC, merged