Remove project persistence.
ActiveState/cli pull request #3347
Opened 2024-06-07 14:56 UTC by mitchell-as

2024-06-07 16:54 UTC, mitchell-as commented
The lone test failure is due to one of the usual timeouts, and is unrelated to this PR.

2024-06-07 21:09 UTC, mitchell-as commented
Test failures are the usual timeouts and unrelated to this PR.

2024-06-10 17:14 UTC, Naatan requested changes

2024-06-10 17:14 UTC, Naatan commented on pkg/projectfile/projectfile.go
> +	}
projectfile should not be dealing with output. I think we could put this in main. Maybe create a `deprecation.go` file where we can place warnings like this.

2024-06-10 17:41 UTC, Naatan approved these changes

2024-06-10 17:57 UTC, merged