Initial ability to `state install` anything.
ActiveState/cli pull request #3383
Opened 2024-07-01 20:14 UTC by mitchell-as

2024-07-01 21:49 UTC, mitchell-as commented on internal/runbits/requirements/install.go
> +package requirements
I am starting the refactor of the monolithic `ExecuteRequirementsOperation()` here. The responsibility of this file is simply to handle installing requirements. I envision another file, _uninstall.go_, having the responsibility of uninstalling requirements.

2024-07-01 21:52 UTC, mitchell-as commented on test/integration/package_int_test.go
> +		cp := ts.Spawn("install", "argpars")
See https://activestatef.atlassian.net/browse/DX-2805?focusedCommentId=53790 for an explanation of why this changed.

2024-07-01 21:52 UTC, mitchell-as commented on test/integration/package_int_test.go
> +		e2e.OptArgs("install", "Charset-normalizer"),
See https://activestatef.atlassian.net/browse/DX-2805?focusedCommentId=53790 for an explanation of why this changed.

2024-07-01 22:29 UTC, mitchell-as commented on internal/runbits/requirements/rationalize.go
> +		*err = errs.WrapUserFacing(*err, strings.Join(messages, "\n"), errs.SetInput())
Yes, the use of tab characters for formatting is awful, but our errors and user-facing errors mechanism expects strings, not objects, so I cannot pass the usual struct with tags to print nicely as a table. I'm open to suggestions or a redo of the mockup.

2024-07-01 22:46 UTC, mitchell-as commented on test/integration/install_int_test.go
> +	cp := ts.Spawn("install", "dataa")
See https://activestatef.atlassian.net/browse/DX-2805?focusedCommentId=53790 for a description of why this changed.

2024-07-02 18:19 UTC, mitchell-as commented
I'm putting this up for early review due to my comment here: https://activestatef.atlassian.net/browse/DX-2805?focusedCommentId=53790. I don't know if it constitutes a blocker or not. Please read through my annotations in this PR too, as they provide context. Also, I'm unsure how to emit a structured output error object.

2024-07-03 16:54 UTC, Naatan requested changes
@mitchell-as let's move the story back to triage so we can discuss how we want to handle it.

There's a couple of implications here both for product and the user experience, as well as for the technical planning / maintainability of the feature. I think it's likely we'll want to pivot a little and probably split this off into multiple stories.

I like where you're headed with the refactor, I imagine we can still iterate on what you started here!

2024-07-15 21:01 UTC, mitchell-as commented
@Naatan since brought the ticket back into the sprint, please re-review with the discussion in mind. I'm unsure how it affects your comment.

2024-07-15 21:05 UTC, mitchell-as commented
Actually, never mind. I have to stop making suggestions first.

2024-07-15 22:30 UTC, mitchell-as commented
Test failures are known and not caused by this PR.

2024-07-15 22:32 UTC, mitchell-as commented
@Naatan since we brought the ticket back into the sprint, please re-review with the discussion in mind. I'm unsure how it affects your comment.

The only change since your last review is that we're only fetching suggestions if the project has one language (https://github.com/ActiveState/cli/pull/3383/commits/1870c3f6c655b3ef35905a8e007b81361b810d78).

2024-07-16 16:44 UTC, Naatan requested changes
I think we should address a refactor of the requirement runbit first. You've started it here but I don't think the stage you're at is one I'm comfortable committing, as it essentially leaves us maintaining two very similar implementations; the new `Install()` and the old `ExecuteRequirementOperation()`. I'd rather we push the refactor through far enough that we don't have two diverging implementations. I'm not saying they should all use the same operation, but under the hood the logic should be shared and not duplicated.

I feel like this is too much scope creep for your story, as refactoring the requirements package ought to involve a bit more strategy and planning. I'd suggest blocking this story on the refactor unless you see another path.

2024-07-17 19:09 UTC, closed without merging

2024-07-17 19:10 UTC, mitchell-as commented
Okay, I've blocked the ticket on the ExecuteRequirementOperation refactor. Once that's done, I'll open a new PR.