Added `state export buildplan`.
ActiveState/cli pull request #3398
Opened 2024-07-15 17:57 UTC by mitchell-as

2024-07-15 19:25 UTC, mitchell-as commented on internal/runbits/buildplanner/buildplanner.go
> +package buildplanner
This was extracted from the artifacts runner. It was fetching a commit and returning the commit's build plan. This runbit has two functions: GetCommit and GetBuildPlan. The logic is unchanged, but broken up into two functions.

2024-07-17 16:48 UTC, MDrakos requested changes
Looks good just one very minor change.

2024-07-17 16:48 UTC, MDrakos commented on cmd/state/internal/cmdtree/export.go
> +		locale.Tl("export_buildplan_title", "Build Plan"),
I believe the other export commands have titles like `Exporting <thing>`
```suggestion
		locale.Tl("export_buildplan_title", "Exporting Build Plan"),
```

2024-07-17 19:58 UTC, mitchell-as commented
Test failure is known and not related to this PR.

2024-07-17 19:58 UTC, mitchell-as commented
I applied your suggestion and fixed a merge conflict. There were no other changes.

2024-07-17 20:07 UTC, MDrakos approved these changes

2024-07-18 16:07 UTC, merged