Remove Windows shortcuts during uninstall.
ActiveState/cli pull request #3439
Opened 2024-08-05 17:33 UTC by mitchell-as

2024-08-05 20:37 UTC, mitchell-as commented on internal/osutils/autostart/autostart_windows.go
>  }
This bug gave me hours of grief :cry:

2024-08-05 20:37 UTC, mitchell-as commented on internal/osutils/autostart/autostart_windows.go
>  }
This bug gave me hours of grief :cry:

2024-08-06 16:49 UTC, MDrakos requested changes

2024-08-06 16:49 UTC, MDrakos commented on test/integration/uninstall_int_test.go
> +		shortcutDir := filepath.Join(ts.Dirs.HomeDir, "AppData", "Roaming", "Microsoft", "Windows", "Start Menu", "Programs", "ActiveState")
Are we verifying that this file exists after install? Otherwise this could be a false positive.

2024-08-06 17:26 UTC, mitchell-as commented
Fair enough. I knew it was getting deleted through manual testing, but it doesn't hurt to have it in a test either.

2024-08-06 18:03 UTC, MDrakos approved these changes

2024-08-06 18:07 UTC, merged