Added `state upgrade`
ActiveState/cli pull request #3467
Opened 2024-08-28 18:25 UTC by Naatan

2024-08-28 21:51 UTC, Naatan commented on pkg/buildplan/artifact_test.go
> -				"00000000-0000-0000-0000-000000000001",
The old assertion failed due to my fix here:

https://github.com/ActiveState/cli/pull/3467/files#diff-9a4a1ec82a2498e8c04daf3594acd7e9f1de41731d7ef7539864881784a5c5c9R270

Before that you would get artifacts that had technically already been "seen". ie. asking for deps on artifact ID `1` would return `1`. Which is not expected (and ironically; also a cycle).

2024-08-29 20:13 UTC, MDrakos requested changes
This looks great to me, just some minor comments and one question.

I would also recommend running the `cve` integration tests as well as any that depend on change summaries just to ensure that the changes there didn't affect anything.

2024-08-29 20:13 UTC, MDrakos commented on internal/sliceutils/sliceutils.go
> +func EqualValues[S ~[]E, E cmp.Ordered](a, b S) bool {
nit: Unit test for this function would be nice.

2024-08-29 20:16 UTC, Naatan commented on internal/locale/locales/en-us.yaml
> +name:
No, the resets act on everything. It's basically telling the shell "go back to normal rendering".

2024-08-29 20:16 UTC, Naatan commented on internal/runners/upgrade/upgrade.go
> +		panic(fmt.Sprintf("bumped buildscript is same as local commit, old: %s, new: %s", bumpedBS.AtTime(), localCommit.BuildScript().AtTime()))
Woops, it is indeed leftover. Thanks for spotting!

2024-08-29 20:31 UTC, MDrakos approved these changes

2024-08-29 20:46 UTC, merged