Narrow detection of activated state.
ActiveState/cli pull request #3533
Opened 2024-10-08 18:29 UTC by mitchell-as

Do not rely on just config, which may be leftover from a previous activation.

Note: I do not have the means to reproduce this issue. My Windows VM cannot run WSL due to the lack of a hypervisor. However, after reading the code (https://github.com/ActiveState/cli/blob/af3779a135fa05b4b31e5dea19a8c8280b4b4403/internal/process/process.go#L130-L132 and https://github.com/ActiveState/cli/blob/af3779a135fa05b4b31e5dea19a8c8280b4b4403/internal/process/process.go#L24-L71), I see that we're relying on a config check, followed by a process ID running check. I think it's possible for a previous activation to be erroneously detected as still running under the right circumstances. The fact that Antoine could not immediately reproduce this issue when filing the initial bug report lends credence to my suspicion.

We may want to consider simplifying this detection to just look for environment variables. I was not present when this detection was initially written, so I don't know exactly why we need it or how accurate it needs to be; it just looks very convoluted to me.

2024-10-08 18:45 UTC, mitchell-as commented
I'm not saying that my approach is correct. I'm open to feedback, a different approach, this being rejected, etc. Do keep in mind I do not have access to WSL from my Windows VM though.

2024-10-08 19:00 UTC, mitchell-as commented
Test failure a timeout and unrelated to this PR.

2024-10-10 17:06 UTC, Naatan requested changes
This feels like we're working around an issue. And it's adding the env var back to detecting activations, which historically has given us lots of issues. IIRC that's the reason we started identifying processes instead.

I'd strongly prefer we try to simplify this mechanic rather than add more complexity to it. If we have a repro case of the issue; can we figure out why the pidfile still exists, and address that?

Also we could probably enrich the config pidfile approach by still verifying the process name. I think if we own the process then we shouldn't see permission errors.

Please always tag me for review on tickets like this. The solution proposed here has lots of implications and goes beyond a bug fix, and was not prescribed in the original ticket. That doesn't mean I'm against it by default or anything, but I'd like to at the very least be aware of the change.

2024-10-15 14:56 UTC, mitchell-as commented
Closing, as I do not have the ability to reproduce this or debug it further.

2024-10-15 14:56 UTC, closed without merging