Handle more buildplanner errors
ActiveState/cli pull request #3547
Opened 2024-10-17 20:51 UTC by MDrakos

2024-10-18 20:00 UTC, MDrakos commented on pkg/platform/api/buildplanner/response/commit.go
> +type ValidationError struct{}
We now have multiple errors with `SubErrors` so I moved that to the common `Error` struct

2024-10-18 20:01 UTC, MDrakos commented
I found that a lot of the errors we are currently handling wouldn't be very enriched by the extra fields. I also took the time in this PR to handle errors that we weren't before.

2024-10-21 17:25 UTC, Naatan requested changes
We should be using the rationalizer for this. These are already returning typed errors, which are at least to some level already rationalized. Adding localized errors underneath them feels inappropriate. We should only be marking input errors outside of rationalizers if there is a clear reason why rationalizing doesn't work there.

2024-10-24 22:06 UTC, MDrakos commented
Closing this PR and filed another story that I think will better address our buildplanner error handling.

2024-10-24 22:06 UTC, closed without merging