Handle more panics
ActiveState/cli pull request #3577
Opened 2024-11-01 20:01 UTC by MDrakos

2024-11-01 20:56 UTC, MDrakos commented on internal/poller/poller.go
> +	}
Panics can occur in the goroutine where the poll func is started. If we don't want this automatic wrapping we can update each caller of this library to manually inject it into their pollfunc.

2024-11-05 17:37 UTC, Naatan requested changes

2024-11-05 17:37 UTC, Naatan commented on cmd/state-svc/internal/messages/messages.go
> +		return nil, errs.New("Could not get messages from cache")
```suggestion
		return nil, errs.New("cacheValue has unexpected type: %T", cacheValue)
```

2024-11-05 17:37 UTC, Naatan commented on cmd/state-svc/internal/messages/messages.go
> +				return nil, errs.New("Could not get last reported time for message %s as it's not a string", message.ID)
```suggestion
				return nil, errs.New("Could not get last reported time for message %s as it's not a string: %T", message.ID, lastReport)
```

2024-11-05 17:37 UTC, Naatan commented on internal/poller/poller.go
> +	}
I think we need to implement this as part of the pollFunc that we pass. Reason being that if we catch it here the stacktrace won't point to what caused the panic.

2024-11-05 23:01 UTC, Naatan approved these changes

2024-11-05 23:07 UTC, merged