Exit with code 11 on user network issues
ActiveState/cli pull request #946
Opened 2020-09-03 18:50 UTC by Naatan

https://www.pivotaltracker.com/story/show/174609340

2020-09-03 21:42 UTC, daved requested changes

2020-09-03 23:19 UTC, Naatan commented on internal/retryhttp/client.go
> +		return res, locale.WrapInputError(&userNetworkError{-1}, "err_user_network_timeout", "Request failed due to timeout. {{.V0}}", solutionLocale)
THe `-1` is setting `_testCode`, not exitCode.

2020-09-04 01:11 UTC, daved approved these changes

2020-09-04 17:11 UTC, daved approved these changes

2020-09-04 17:15 UTC, merged